### ISSUE TITLE
[feat] add filter for routes

### ISSUE THREAD

**Issue by hewliyang** [hewliyang/nus-nextbus-web#5]
check route for contains {..stop}

**Comment by aoi-ue** [comment]
Hi Li Yang, will you implement this? Would like to contribute on this.

**Comment by hewliyang** [comment]
> Hi Li Yang, will you implement this? Would like to contribute on this.

I wont, so feel free to do so if you would like to. But I don't think many people use this site anymore since the original domain expired.

Instead, you may want to have a look at https://github.com/nusmodifications/nusmods/pull/3712 where some people are working on integrating something similar as part of NUSMods. 

Cheers
